# Generated by Django 5.1.2 on 2024-10-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FutaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EiNumber', models.CharField(max_length=9)),
                ('LegalName', models.CharField(max_length=50)),
                ('ComercialName', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.CharField(max_length=5)),
                ('ForeignCountry', models.CharField(blank=True, max_length=50, null=True)),
                ('ForeignState', models.CharField(blank=True, max_length=50, null=True)),
                ('ForeignZip', models.CharField(blank=True, max_length=5, null=True)),
                ('DeclarationType', models.CharField(choices=[('a', 'Enmendada'), ('b', 'Empleador sucesor'), ('c', 'Ningun pago hecho a los empleados en 2023'), ('d', 'Final: se cerro el negocio o dejo de pagar salarios')], default='a', max_length=2)),
                ('Pt1A', models.CharField(max_length=2)),
                ('Pt1B', models.BooleanField()),
                ('Pt12', models.BooleanField()),
                ('TotalEmployePayment', models.CharField(blank=True, max_length=50, null=True)),
                ('ExentPayment', models.CharField(blank=True, max_length=50, null=True)),
                ('SupplementaryBenefits', models.BooleanField()),
                ('LifeInsurance', models.BooleanField()),
                ('Retire', models.BooleanField()),
                ('DependantsCare', models.BooleanField()),
                ('Other', models.BooleanField()),
                ('ExcessPayment', models.CharField(blank=True, max_length=50, null=True)),
                ('SubtotalPayment', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalSalary', models.CharField(blank=True, max_length=50, null=True)),
                ('FutaFeePreAdjust', models.CharField(blank=True, max_length=50, null=True)),
                ('FutaSalaryTotalFee', models.CharField(blank=True, max_length=50, null=True)),
                ('SomesalaryFuta', models.CharField(blank=True, max_length=50, null=True)),
                ('CreditReduction', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalFutaFeeAfterAdjust', models.CharField(blank=True, max_length=50, null=True)),
                ('FutaFeeYearIncludingExcess', models.CharField(blank=True, max_length=50, null=True)),
                ('BalanceDue', models.CharField(blank=True, max_length=50, null=True)),
                ('ExcessPayment2', models.CharField(blank=True, max_length=50, null=True)),
                ('ApplyNextStatement', models.BooleanField()),
                ('SendRefund', models.BooleanField()),
                ('FirstTrimester', models.CharField(blank=True, max_length=50, null=True)),
                ('SecondTrimester', models.CharField(blank=True, max_length=50, null=True)),
                ('ThirdTrimester', models.CharField(blank=True, max_length=50, null=True)),
                ('FourthTrimester', models.CharField(blank=True, max_length=50, null=True)),
                ('TotalTaxLiability', models.CharField(blank=True, max_length=50, null=True)),
                ('IRSEmployAllow', models.BooleanField()),
                ('IRSPinNumber', models.CharField(blank=True, max_length=5, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Position', models.CharField(blank=True, max_length=50, null=True)),
                ('PhoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('SelfEmploy', models.BooleanField()),
                ('PreparerName', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerCompanyName', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerCity', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerState', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerZip', models.CharField(blank=True, max_length=5, null=True)),
                ('PreparerPTIN', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerEIN', models.CharField(blank=True, max_length=50, null=True)),
                ('PreparerPhone', models.CharField(blank=True, max_length=11, null=True)),
                ('PaymentAmountD', models.CharField(blank=True, max_length=50, null=True)),
                ('PaymentAmountC', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
