# Generated by Django 5.1.2 on 2024-10-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futamodel',
            name='DeclarationType',
        ),
        migrations.RemoveField(
            model_name='futamodel',
            name='Pt1A',
        ),
        migrations.AddField(
            model_name='futamodel',
            name='DeclarationA',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='DeclarationB',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='DeclarationC',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='DeclarationD',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='IRSEmployName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='IRSEmployPhone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='Pt1A1',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='futamodel',
            name='Pt1A2',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='ApplyNextStatement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='DependantsCare',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='IRSEmployAllow',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='LifeInsurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='Other',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='Pt12',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='Pt1B',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='Retire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='SelfEmploy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='SendRefund',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futamodel',
            name='SupplementaryBenefits',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
